api_key: null
cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name
credentials:
  roles:
    admin:
      usernames:
      - jdoe
      - jsmith
  usernames:
    jdoe:
      email: jdoe@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Doe
      logged_in: false
      password: $argon2id$v=19$m=65536,t=3,p=4$T/Xrwym16fOVYNIjU9Wd6A$nKxrm+S4BzjIf8PoeMD3ZoygxrKCg3BWngQGIYvfFxc
      roles:
      - admin
      - editor
      - viewer
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $argon2id$v=19$m=65536,t=3,p=4$NNktseiPYxznMWEbV0HcXw$mNQEpMXbLx1LtPc0PF1rajqEuJ2LA6W31DExP9YxtY8
      roles:
      - admin
      - editor
      - viewer
    test:
      email: test@email.com
      failed_login_attempts: 0
      first_name: test
      last_name: test
      logged_in: false
      password: $argon2id$v=19$m=65536,t=3,p=4$Yzj15yEDsLErbRbXocLJqw$2bhGkUkcTV8Ann2YoDEEPzHQgFxOio7t1TZXHQNazic
      password_hint: std
      roles:
      - viewer
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
